### ISSUE TITLE
fetch_data('iris') returns an error

### ISSUE THREAD

**Issue by shahyash10** [EpistasisLab/pmlb#148]
- pmlb version `1.0.2a0` and `1.0.1.post3` (fails on both)
 - Issue exists on both macos big sur and WSL ubuntu, both from within a miniconda environment
 - python version `3.9.2`
 - Code to recreate:
```
 >>> from pmlb import fetch_data
>>> z = fetch_data('iris')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yashs97/miniconda3/envs/EGADS/lib/python3.9/site-packages/pmlb/pmlb.py", line 80, in fetch_data
    dataset = pd.read_csv(dataset_url, sep='\t', compression='gzip')
  File "/home/yashs97/miniconda3/envs/EGADS/lib/python3.9/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/yashs97/miniconda3/envs/EGADS/lib/python3.9/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/yashs97/miniconda3/envs/EGADS/lib/python3.9/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/yashs97/miniconda3/envs/EGADS/lib/python3.9/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/yashs97/miniconda3/envs/EGADS/lib/python3.9/site-packages/pandas/io/parsers.py", line 1898, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 518, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 620, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 814, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1943, in pandas._libs.parsers.raise_parser_error
  File "/home/yashs97/miniconda3/envs/EGADS/lib/python3.9/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/yashs97/miniconda3/envs/EGADS/lib/python3.9/gzip.py", line 487, in read
    if not self._read_gzip_header():
  File "/home/yashs97/miniconda3/envs/EGADS/lib/python3.9/gzip.py", line 435, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')

```

**Comment by shahyash10** [comment]
@lacava Is this something you can please help out with? Thanks!

**Comment by lacava** [comment]
i'm getting the same error on a fresh install. may have to do with going over our LFS bandwidth quota for the month. https://github.com/EpistasisLab/pmlb/runs/2392306391?check_suite_focus=true#step:5:4

**Comment by lacava** [comment]
@yashs97  can you try now? (we bought more storage, working for me now)

**Comment by shahyash10** [comment]
Its working for me as well, thanks so much @lacava
